---
- name: Deploy Spring Boot and MySQL on EC2
  hosts: all
  become: yes
  tasks:
    - name: Run MySQL Docker container
      docker_container:
        name: mysql
        image: mysql:8.0
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: coinxcel_db
          MYSQL_USER: user
          MYSQL_PASSWORD: userpassword
        published_ports:
          - "3306:3306"
      when: inventory_hostname == "mysql-instance"

    - name: Run Spring Boot Docker container
      docker_container:
        name: springboot
        image: ${REPO_NAME}/coinxcel-server
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
      when: inventory_hostname == "springboot-instance"
